[tool.poetry]
name = "zulip-gtk"
version = "0.1.0"
description = "Zulip GTK"
authors = ["Hannes <h@nnes.dev>"]

[tool.poetry.dependencies]
python = "^3.9"
PyGObject = "^3.42.0"
zulip = "^0.8.1"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.12b0"
mypy = "^0.930"
flake8 = "^4.0.1"
pydocstyle = "^6.1.1"
# pygobject-stubs = { git = "https://github.com/pygobject/pygobject-stubs" }

[tool.pyright]
include = ["zulip_gtk"]
typeCheckingMode = "basic"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
